// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_slopeSolver_RCPPEXPORTS_H_GEN_
#define RCPP_slopeSolver_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace slopeSolver {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("slopeSolver", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("slopeSolver", "_slopeSolver_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in slopeSolver");
            }
        }
    }

    inline arma::vec FastProxSL1(arma::vec y, arma::vec lambda) {
        typedef SEXP(*Ptr_FastProxSL1)(SEXP,SEXP);
        static Ptr_FastProxSL1 p_FastProxSL1 = NULL;
        if (p_FastProxSL1 == NULL) {
            validateSignature("arma::vec(*FastProxSL1)(arma::vec,arma::vec)");
            p_FastProxSL1 = (Ptr_FastProxSL1)R_GetCCallable("slopeSolver", "_slopeSolver_FastProxSL1");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_FastProxSL1(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec solveSlope(arma::mat x, arma::vec y, arma::vec lambda) {
        typedef SEXP(*Ptr_solveSlope)(SEXP,SEXP,SEXP);
        static Ptr_solveSlope p_solveSlope = NULL;
        if (p_solveSlope == NULL) {
            validateSignature("arma::vec(*solveSlope)(arma::mat,arma::vec,arma::vec)");
            p_solveSlope = (Ptr_solveSlope)R_GetCCallable("slopeSolver", "_slopeSolver_solveSlope");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_solveSlope(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

}

#endif // RCPP_slopeSolver_RCPPEXPORTS_H_GEN_
