# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastProxSL1 <- function(y, lambda) {
    .Call(`_slopeSolver_FastProxSL1`, y, lambda)
}

rcpparma_hello_world <- function() {
    .Call(`_slopeSolver_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_slopeSolver_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_slopeSolver_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_slopeSolver_rcpparma_bothproducts`, x)
}

solveSlope <- function(x, y, lambda) {
    .Call(`_slopeSolver_solveSlope`, x, y, lambda)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_slopeSolver_RcppExport_registerCCallable', PACKAGE = 'slopeSolver')
})
